import type { Goallet } from "./types";

export const goalletsIniciales: Goallet[] = [
  {
    id: "fondo-respaldo",
    nombre: "Fondo de Respaldo",
    objetivo: "Respaldo financiero para imprevistos operativos y de liquidez personal",
    icono: "shield",
    montoMeta: 10000,
    montoActual: 6183.25,
    aportePeriodicoSugerido: 150,
    tasaTNA: 5.25,
    tasaTEA: 5.38,
    bloqueado: false,
    fechaLimite: "2026-12-01",
    creadoEn: "2025-09-01",
    boosters: [
      {
        id: "ahorro-mensual",
        titulo: "Ahorro mensual",
        descripcion: "Aporta $150,00 el día 1 de cada mes al acreditarse el sueldo.",
        icono: "calendar_today",
        activo: true,
        etiqueta: "ACTIVO",
      },
      {
        id: "blindaje-tasa",
        titulo: "Blinda tu tasa",
        descripcion: "Fija un monto a plazo preferencial por 90 días con rendimiento extra garantizado de 6.50% TNA.",
        icono: "lock_clock",
        activo: false,
        etiqueta: "DISPONIBLE",
      },
    ],
    movimientos: [
      {
        id: "m1",
        tipo: "rendimiento",
        descripcion: "Interés mensual acreditado",
        origen: "Rendimiento",
        monto: 9,
        fecha: "2026-03-01T08:30:00",
        saldoResultante: 6183.25,
      },
      {
        id: "m2",
        tipo: "aporte",
        descripcion: "Aporte automático programado",
        origen: "Ahorro Mensual",
        monto: 150,
        fecha: "2026-03-01T01:00:00",
        saldoResultante: 6174.25,
      },
      {
        id: "m3",
        tipo: "aporte",
        descripcion: "Aporte voluntario de liquidez",
        origen: "Transferencia Inmediata",
        monto: 500,
        fecha: "2026-02-15T14:15:00",
        saldoResultante: 6024.25,
      },
    ],
  },
  {
    id: "viaje-bariloche",
    nombre: "Viaje a Bariloche",
    objetivo: "Vacaciones familiares de una semana en la Patagonia",
    icono: "flight_takeoff",
    montoMeta: 2500,
    montoActual: 980,
    aportePeriodicoSugerido: 120,
    tasaTNA: 4.1,
    tasaTEA: 4.18,
    bloqueado: false,
    fechaLimite: "2026-11-15",
    creadoEn: "2025-11-10",
    boosters: [
      {
        id: "ahorro-mensual",
        titulo: "Ahorro mensual",
        descripcion: "Aporta $120,00 el día 5 de cada mes.",
        icono: "calendar_today",
        activo: true,
        etiqueta: "ACTIVO",
      },
    ],
    movimientos: [
      {
        id: "m1",
        tipo: "aporte",
        descripcion: "Aporte automático programado",
        origen: "Ahorro Mensual",
        monto: 120,
        fecha: "2026-03-05T09:00:00",
        saldoResultante: 980,
      },
      {
        id: "m2",
        tipo: "aporte",
        descripcion: "Aporte voluntario",
        origen: "Transferencia Inmediata",
        monto: 200,
        fecha: "2026-02-20T11:20:00",
        saldoResultante: 860,
      },
    ],
  },
  {
    id: "auto-nuevo",
    nombre: "Auto Nuevo",
    objetivo: "Cuota inicial para la compra de un vehículo 0km",
    icono: "directions_car",
    montoMeta: 15000,
    montoActual: 3400,
    aportePeriodicoSugerido: 300,
    tasaTNA: 5.6,
    tasaTEA: 5.75,
    bloqueado: true,
    tasaTNASinBloqueo: 4.5,
    tasaTEASinBloqueo: 4.58,
    fechaLimite: "2027-06-01",
    creadoEn: "2025-06-01",
    boosters: [
      {
        id: "blindaje-tasa",
        titulo: "Blinda tu tasa",
        descripcion: "Fondos bloqueados por 12 meses con rendimiento extra garantizado de 5.60% TNA.",
        icono: "lock_clock",
        activo: true,
        etiqueta: "ACTIVO",
      },
    ],
    movimientos: [
      {
        id: "m1",
        tipo: "aporte",
        descripcion: "Aporte automático programado",
        origen: "Ahorro Mensual",
        monto: 300,
        fecha: "2026-03-01T09:00:00",
        saldoResultante: 3400,
      },
    ],
  },
];

export const iconosDisponibles = [
  "shield",
  "flight_takeoff",
  "directions_car",
  "home",
  "school",
  "celebration",
  "savings",
  "favorite",
];
