graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["System Context View: Sistema de Ahorro Programado"]
    style diagram fill:#ffffff,stroke:#ffffff

    1["<div style='font-weight: bold'>Cliente Bancario</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Usuario que gestiona sus<br />planes de ahorro y realiza<br />simulaciones.</div>"]
    style 1 fill:#08427b,stroke:#052e56,color:#ffffff
    2["<div style='font-weight: bold'>Core Bancario Legacy</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Sistema bancario central que<br />maneja las cuentas asociadas<br />y saldos primarios. Fuera de<br />alcance: se simula con<br />MongoDB (carpeta bdd/).</div>"]
    style 2 fill:#999999,stroke:#6b6b6b,color:#ffffff
    3["<div style='font-weight: bold'>Sistema de Notificaciones</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Servicio externo para envío<br />de SMS y correos.</div>"]
    style 3 fill:#999999,stroke:#6b6b6b,color:#ffffff
    4["<div style='font-weight: bold'>Sistema de Ahorro Programado</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Permite crear, simular,<br />debitar y consultar planes de<br />ahorro.</div>"]
    style 4 fill:#1168bd,stroke:#0b4884,color:#ffffff

    1-. "<div>Simula, crea planes, aporta,<br />retira, bloquea y cancela</div><div style='font-size: 70%'>[HTTPS]</div>" .->4
    4-. "<div>Valida cuentas y ejecuta<br />débitos y créditos (vía<br />adaptador)</div><div style='font-size: 70%'>[SOAP / REST]</div>" .->2
    3-. "<div>Consume eventos de débitos y<br />planes</div><div style='font-size: 70%'>[AMQP]</div>" .->4

  end